services:
  choppa:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - redis
    networks:
      - default
    ports:
      - "8080:8080"
  redis:
    image: redis:7.0.4-alpine3.16
    env_file:
      - .env
    ports:
      - "6379:6379"
    command: redis-server --requirepass $REDIS_PASSWORD